import React, { useState, useEffect } from 'react';
import {
  StyleSheet,
  Text,
  View,
  TouchableOpacity,
  TextInput,
  ScrollView,
  Alert,
  ActivityIndicator,
} from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { Ionicons } from '@expo/vector-icons';
import { COLORS } from '../config';
import { patientAPI } from '../services/api';
import { useAuth } from '../context/AuthContext';

// Generate random patient ID in format "abc-123"
const generatePatientId = (): string => {
  const letters = 'abcdefghijklmnopqrstuvwxyz';
  const numbers = '0123456789';
  
  let id = '';
  // Generate 3 random letters
  for (let i = 0; i < 3; i++) {
    id += letters.charAt(Math.floor(Math.random() * letters.length));
  }
  id += '-';
  // Generate 3 random numbers
  for (let i = 0; i < 3; i++) {
    id += numbers.charAt(Math.floor(Math.random() * numbers.length));
  }
  
  return id;
};

export default function CreatePatientScreen({ navigation }: any) {
  const [fullName, setFullName] = useState('');
  const [patientId, setPatientId] = useState('');
  const [phone, setPhone] = useState('');
  const [email, setEmail] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const { refreshUser } = useAuth();

  // Generate patient ID on component mount
  useEffect(() => {
    setPatientId(generatePatientId());
  }, []);

  const handleCreate = async () => {
    if (!fullName || !patientId) {
      Alert.alert('Required Fields', 'Please fill in patient name and ID');
      return;
    }

    setIsLoading(true);
    try {
      console.log('📝 Creating patient:', { patientId, fullName });
      const result = await patientAPI.create({
        patient_id: patientId,
        full_name: fullName,
        phone: phone || undefined,
        email: email || undefined,
        is_active: true,
      });
      console.log('✅ Patient created:', result);

      // Refresh user data to update patient count
      await refreshUser();

      Alert.alert('Success', 'Patient created successfully', [
        { text: 'OK', onPress: () => navigation.goBack() }
      ]);
    } catch (error: any) {
      console.error('❌ Create patient error:', error);
      console.error('Error details:', error.message);
      Alert.alert('Error', error.message || 'Failed to create patient');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <LinearGradient
      colors={COLORS.backgroundGradient}
      locations={[0, 0.3, 0.7, 1]}
      start={{ x: 0, y: 0 }}
      end={{ x: 1, y: 1 }}
      style={styles.container}
    >
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.backButton}>
          <Ionicons name="arrow-back" size={24} color={COLORS.paleAzure} />
        </TouchableOpacity>
        <Text style={styles.title}>New Patient</Text>
        <View style={{ width: 40 }} />
      </View>

      <ScrollView contentContainerStyle={styles.scrollContent} showsVerticalScrollIndicator={false}>
        <View style={styles.form}>
          <View style={styles.inputGroup}>
            <Text style={styles.label}>Full Name *</Text>
            <TextInput
              style={styles.input}
              value={fullName}
              onChangeText={setFullName}
              placeholder="Enter patient name"
              placeholderTextColor={COLORS.textSecondary}
            />
          </View>

          <View style={styles.inputGroup}>
            <View style={styles.labelRow}>
              <Text style={styles.label}>Patient ID *</Text>
              <TouchableOpacity
                onPress={() => setPatientId(generatePatientId())}
                style={styles.regenerateButton}
              >
                <Ionicons name="refresh" size={16} color={COLORS.saffron} />
                <Text style={styles.regenerateText}>Regenerate</Text>
              </TouchableOpacity>
            </View>
            <View style={styles.idInputContainer}>
              <TextInput
                style={[styles.input, styles.idInput]}
                value={patientId}
                editable={false}
                placeholderTextColor={COLORS.textSecondary}
              />
              <View style={styles.autoGeneratedBadge}>
                <Text style={styles.autoGeneratedText}>Auto-generated</Text>
              </View>
            </View>
          </View>

          <View style={styles.inputGroup}>
            <Text style={styles.label}>Phone</Text>
            <TextInput
              style={styles.input}
              value={phone}
              onChangeText={setPhone}
              placeholder="Enter phone number"
              placeholderTextColor={COLORS.textSecondary}
              keyboardType="phone-pad"
            />
          </View>

          <View style={styles.inputGroup}>
            <Text style={styles.label}>Email</Text>
            <TextInput
              style={styles.input}
              value={email}
              onChangeText={setEmail}
              placeholder="Enter email address"
              placeholderTextColor={COLORS.textSecondary}
              keyboardType="email-address"
              autoCapitalize="none"
            />
          </View>

          <TouchableOpacity 
            style={[styles.createButton, isLoading && styles.createButtonDisabled]} 
            onPress={handleCreate}
            disabled={isLoading}
          >
            {isLoading ? (
              <ActivityIndicator color={COLORS.raisinBlack} />
            ) : (
              <Text style={styles.createButtonText}>Create Patient</Text>
            )}
          </TouchableOpacity>
        </View>
      </ScrollView>
    </LinearGradient>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 60,
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  backButton: {
    padding: 10,
    backgroundColor: COLORS.cardBackground,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: COLORS.borderColor,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.paleAzure,
  },
  scrollContent: {
    paddingHorizontal: 20,
    paddingBottom: 40,
  },
  form: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 20,
    padding: 24,
    borderWidth: 2,
    borderColor: COLORS.borderColor,
  },
  inputGroup: {
    marginBottom: 20,
  },
  labelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: COLORS.paleAzure,
  },
  regenerateButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: 'rgba(227, 181, 5, 0.1)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(227, 181, 5, 0.3)',
  },
  regenerateText: {
    fontSize: 12,
    color: COLORS.saffron,
    marginLeft: 4,
    fontWeight: '500',
  },
  idInputContainer: {
    position: 'relative',
  },
  idInput: {
    backgroundColor: 'rgba(144, 215, 239, 0.05)',
    opacity: 0.8,
  },
  autoGeneratedBadge: {
    position: 'absolute',
    right: 12,
    top: 14,
    backgroundColor: 'rgba(144, 215, 239, 0.2)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  autoGeneratedText: {
    fontSize: 10,
    color: COLORS.paleAzure,
    fontWeight: '600',
  },
  input: {
    backgroundColor: 'rgba(144, 215, 239, 0.1)',
    borderWidth: 2,
    borderColor: COLORS.borderColor,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: COLORS.paleAzure,
  },
  createButton: {
    backgroundColor: COLORS.paleAzure,
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 10,
  },
  createButtonDisabled: {
    opacity: 0.6,
  },
  createButtonText: {
    fontSize: 18,
    fontWeight: '600',
    color: COLORS.raisinBlack,
  },
});
